language: node_js
node_js:
- 6
- 8
cache: yarn
before_script:
- yarn global add codecov
script:
- yarn run eslint
- yarn run cover
after_success:
- codecov
before_deploy: yarn postversion
deploy:
  provider: npm
  email: joe.grund@intel.com
  api_key:
    secure: gtRChkAtSjZPKorMSImjH5si4RPipsnQFCji4MP1F4ESMLiN5/ClrGVw0TInzHHDNG4R1ohF71YRAL1oDRmixjDT3HLc5ZrzWkoVjJMkej5OQkL8GtCFLkgV7nxDFKsyyETUELe0iVu6BcjI09wW9CZkvt1W7ZEM6sUEizhLlCHwImVsv+8stY+UjIfAenhCSrsiW0cVCEksWhnaEFSq2MG4kmp2koI6EZ+olbRTR5WJDTUd1AMuiwW4QNdrYZLlz82j1to/HsBqm+qOpKUoTtSr7NUYj0PfPm77rb7bNB2MCVlAXidhRSgE6t8nmV/AsU1ogaTgkCu/SWMtl2RW3h4fjvBCGwG1o/EVj3iY9vRiKQEzwggPe95iJjc0B0r0TzyjehFQT//4ouNFsj0ZbPAc4jVC76VMoxDOWl7yYtbRgXZrGOd3HqRWYyqFnBZohDzX7m+p96ZzCRjC84xTh1qs1CVU1vt1/lZiDZVNzd8KjjGep+W0I0j0wKceZX4QYC3t0oNBb2mCYHEV9XVrW/qzycztSUut0SvktLZc/iIRfWIL10DeWLA4T7GLOZqbaFyA4th444C0tkkoLNOVHdIRpGc8/UwQLWNttSAgtBoyJWIqbGGbR8L0wSP1vWKVMMFgIfMkPLJRfFtXw9UTEBzCS1D3FfpiCHuuAoCZBrM=
  on:
    tags: true
    repo: intel-hpdd/supervisor-status
