language: node_js
node_js:
- 6
- 8
- 10
cache: yarn
before_script:
- yarn global add codecov
script:
- yarn run eslint
- yarn run cover
after_success:
- codecov
before_deploy: yarn postversion
deploy:
  provider: npm
  email: joe.grund@intel.com
  api_key:
    secure: p96157JzdrqeOKIfecCe2BmCYAGLzYmocud2aVeSDzjvtZcd1lJAwwh+adEAMCtKh+j8vBk/HhbwOtwuJ+MxiHHDlH7Np2/Rt95K/O82MG6urCWXd2oBuv2EXzyXuXfEC4/JzxE19Y387ZemDuMyqWN2HAoZgxgNbT1hweLchjQ2RrrZHbymiEUqRX9W01mFo4gyLNYnySAfml8eIZJeZFfsYz7UlzsKQhkMqMYMN/FS7b061gDNBY1sNNxQbADtCARbCSX0DUnG6JkS6XooAP++RUyuGaC7f2/fOfGdDu2vYUKfCi6YN/GyN/D1U1F5PMtG28PskQJjw4uzUOcKbpjR1gM06AwGyBHYM68De6g5ah0I3eS7wYhe2yaqnz/LQqBSbVUyfTGLmHl3NnUnLS0P609gkgeYfCRzToHpl7KYWRO41yBZtnqvpFXtvPA33aKBWf53StzyaSBlGO+mxcw3LZ9kdbMYyTPgT7D69PCSMg/lhFxG4YmBvG/LNydcxQPChKTA7eRVvzjrVOplBcCwciAVSlPx2NbdGxMMbIB0So4q0OxYiZEjkgblnSR+HOUdOBGYV8ybhU6cc7oVBKzmtc080bXrpf1qNvJzynOMeBKQyiYdUU/9+ZS6qgNeDiGZ3kCFdQOxtvfJamB6dn3ohbmm1o4lm7R0GNzJxx8=
  on:
    tags: true
    repo: intel-hpdd/supervisor-status
